name: armTemplateDeployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Azure deploy ARM template
        uses: Azure/cli@v1
        with:
          inlinescript: |
            az deployment sub create --location "westeurope" --template-file ./arm-templates/resourcegroup.json

      - name: Run a one-line script
        run: echo Čau, lidi!
